spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.3.9:3306/xs_tech?useUnicode=true&autoReconnect=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&useSSL=false
    username: root
    password: "xxxxxx"

  redis:
    host: 127.0.0.1
    port: 6379
    database: 1
    password: xxxxxx
